import { CxIcon } from './build/cx-icon.model';
export declare type CxIconNameSubset<T extends Readonly<CxIcon[]>> = T[number]['name'];
export * from './build/cxIcon-add_chart.icon';
export * from './build/cxIcon-add_comment.icon';
export * from './build/cxIcon-align_horizontal_center.icon';
export * from './build/cxIcon-align_horizontal_left.icon';
export * from './build/cxIcon-computer-engineering.icon';
export * from './build/cxIcon-mechanical-engineering.icon';
export * from './build/completeIconSet';
export * from './build/cx-icon.model';
